# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_obj',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
