# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20170718_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_obj', models.FileField(blank=True, upload_to='firstapp/static')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
